version: "3"
services:
  web:
    build: .
    command: python -m flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_APP=app/hello.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
